# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: '早稲田大学について',  url: 'about-waseda/'}
- {name: '学業生活',           url: 'academic-life/'}
- {name: 'キャンパスライフと施設',       url: 'campus-info/'}
- {name: '東京での生活',      url: 'tokyo-life/'}
- {name: '留学生支援',              url: 'international-student-support/'}
- {name: '学生体験談',            url: 'student-experiences/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://example.com'}
- {icon: 'facebook', link:   'https://example.com'}
- {icon: 'instagram', link:  'https://example.com'}
- {icon: 'envelope', link:   'https://example.com'}
- {icon: 'rss-square', link: 'https://example.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text


